name: Generate LDoc
on:
  push:
    branches: [ main ] # Runs every time you push to main

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Documentation
        uses: lunarmodules/ldoc@v1.5.0
        with:
          args: . # Scans the current folder for all .lua files

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc # LDoc outputs to a folder named 'doc' by default
